### ISSUE TITLE
Crash when clicking the 'next page arrow' on the wildwood armor page.

### ISSUE THREAD

**Issue by laserlemons** [elucent/Roots#1]
http://pastebin.com/RvuBqtbW
![2016-06-13_21 39 22](https://cloud.githubusercontent.com/assets/6501298/16031385/596f57bc-31af-11e6-8f0e-7b88de08e67e.png)

**Comment by Kaisoul** [comment]
i also crashed while looking at the wooden armor and hitting the next arrow.
[crash-2016-06-14_00.26.26-client.txt](https://github.com/elucent/Roots/files/313209/crash-2016-06-14_00.26.26-client.txt)

**Comment by elucent** [comment]
I _think_ this is fixed. Looks like I had "Blocks.WHEAT" instead of "Items.WHEAT" in the recipe. Thank you for letting me know about this so quickly!
