### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Roxforbraynz** [elucent/Roots#10]
[Crash log](http://pastebin.com/mJkJc9Xh)

Forge 1.9.4-12.17.0.1963
Roots 0.003

**Comment by cauliflower69** [comment]
Same issue here http://pastebin.com/6ZvweDeK

**Comment by tkdberger** [comment]
can confirm, have same issue on 0.003

**Comment by elucent** [comment]
The jarfile uploaded to Curse wasn't compiled correctly. A new version has been uploaded and, according to my tests, shouldn't cause that problem.

**Comment by tkdberger** [comment]
Things move fast with this mod, I see.
