### ISSUE TITLE
Small area in the tablet GUI that will highlight 2 selections at the same time.

### ISSUE THREAD

**Issue by laserlemons** [elucent/Roots#12]
![2016-06-14_12 01 32](https://cloud.githubusercontent.com/assets/6501298/16056335/e5718788-3229-11e6-851d-d575729191cf.png)

It only looks like it's this row. It highlights the text for both icons. My mouse is pointed at the very bottom of the 'Component: Healing' icon.

**Comment by elucent** [comment]
I don't think I was separating the buttons by the right amount in their collision boxes. It should be fixed for the next version.
