### ISSUE TITLE
Combining a stick and petal dust in the Imbuer crashes

### ISSUE THREAD

**Issue by BootyToast** [elucent/Roots#13]
I did as the tablet said and I was met with a crash :/ It doesn't matter the order in which they are placed.

**Comment by elucent** [comment]
Crash log? I was using them earlier today while playtesting and nothing bad happened.

**Comment by BootyToast** [comment]
[crash-2016-06-14_19.24.08-server.txt](https://github.com/elucent/Roots/files/315148/crash-2016-06-14_19.24.08-server.txt)

**Comment by TehNut** [comment]
https://github.com/elucent/Roots/blob/master/src/main/java/elucent/roots/tileentity/TileEntityImbuer.java#L138

`ItemStack#getTagCompound()` is always null unless set somewhere else. So unless you are 100% sure that you have set it previously, make sure to check `ItemStack#hasTagCompound()` before attempting to get a tag.

**Comment by elucent** [comment]
I didn't check hasTagCompound() because it _should_ be impossible to obtain petal dust without an NBT tag. Using /give or something could produce this bug, though.

I've added safety checks for the next commit.
