### ISSUE TITLE
Crash when using Nature's Cure Staff

### ISSUE THREAD

**Issue by BootyToast** [elucent/Roots#18]
I know I've been posting a lot here lately, but I've been playing the heck out of this.
Tried to use Nature's Cure to combat Soul Fray, but after testing it turns out it crashed anytime it's used.
Crash report: http://pastebin.com/7paYT3e4

**Comment by elucent** [comment]
Soul Fray, not being a vanilla potion effect, won't give any positive buffs when cured, though it should still be removable by the spell (unless BM has special protections on it, which is possible). Just FYI.

This has been fixed in the latest commit, and a new jarfile will be released soon.
