### ISSUE TITLE
Imbuer and Bark Knife both have a picture of a Mortar as their crafting output on their pages of the Runic Tablet.

### ISSUE THREAD

**Issue by laserlemons** [elucent/Roots#2]
![2016-06-13_21 37 45](https://cloud.githubusercontent.com/assets/6501298/16031362/205fed42-31af-11e6-865d-135fe65a0233.png)
![2016-06-13_21 37 54](https://cloud.githubusercontent.com/assets/6501298/16031363/23d837d6-31af-11e6-83a2-4bc2e6791bbc.png)

**Comment by elucent** [comment]
Oh, whoops, I fixed this before I saw that you'd done it for me.
