### ISSUE TITLE
Missing Lang Strings

### ISSUE THREAD

**Issue by xMrVizzy** [elucent/Roots#20]
Can you add all this strings in the lang file, please.
![screenshot_1](https://cloud.githubusercontent.com/assets/7906418/16114480/e986648a-33da-11e6-9fb4-7e6cf9415287.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/7906418/16114481/e988a538-33da-11e6-836e-2080e4dcbd21.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/7906418/16114482/e98ba562-33da-11e6-9893-d86f978bf229.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/7906418/16114507/0ce5d2e4-33db-11e6-82e4-5b5e58aca9e7.png)

And Runed Table text too!

**Comment by elucent** [comment]
I'll start working on it. The actual researches will probably take quite some time, since I didn't exactly code them very well.

**Comment by xMrVizzy** [comment]
Okay! I will help you with it and with JEI Support too!

**Comment by xMrVizzy** [comment]
@elucent rate this. How it looks?
![screenshot_1](https://cloud.githubusercontent.com/assets/7906418/16133533/d85e46bc-3431-11e6-8b4a-86ef81e127f9.png)

**Comment by elucent** [comment]
Overall that looks pretty good, though the verdant sprig texture could be a bit leafier. When I get the time I could take a look at it.

**Comment by xMrVizzy** [comment]
Okay :+1:

**Comment by elucent** [comment]
Just an update: I have all the prerequisite code for the language localization, but I need to finish rewriting it into the lang file.

**Comment by xMrVizzy** [comment]
Yes, and... ?

**Comment by elucent** [comment]
Just sharing my progress so far. I should be able to close this issue once I have the time to finish rewriting everything.

**Comment by xMrVizzy** [comment]
Okay, good job, and i wait 1.10 version :)

**Comment by xMrVizzy** [comment]
I know it's simple! Transfer mod from 1.9.4 to 1.10 easy!

**Comment by elucent** [comment]
Localization support has been added! It'll be in the next commit/release later today, I just need to add another oft-requested feature: config options.

**Comment by xMrVizzy** [comment]
Yay!

**Comment by xMrVizzy** [comment]
Can't wait :)
