### ISSUE TITLE
[Suggestion] Buff Growth

### ISSUE THREAD

**Issue by Ayrrow** [elucent/Roots#21]
As per title, could you buff the growth spell? Currently with 1 Glowstone the spell feels very weak - and it doesn't always fire. It would be extremely useful to get this effect in the early game.

**Comment by elucent** [comment]
It's intentionally a bit weak, since it's a fairly cheap spell. Keep in mind that it grows in a slight AoE, so make sure to target areas with many crops nearby.

**Comment by elucent** [comment]
You know what, a small buff actually sounds like a good idea. Nothing crazy, and it still might not work every time, but it will be 20-30% stronger in the near future.

**Comment by Ayrrow** [comment]
Thats all it really needs.

**Comment by elucent** [comment]
Just FYI, a new release should be out relatively soon. This weekend seems like a good estimate at the time of writing this. I'll include a buffed growth spell in that.
