### ISSUE TITLE
Suggestion - Config to disable the runic tablet animation

### ISSUE THREAD

**Issue by Peach774** [elucent/Roots#23]
The animation inside the runic tablet makes me sick. I get motion sick from seeing it. Can you please add a config to disable it?

**Comment by elucent** [comment]
Sure. It'll be in the next release, along with a possible animation change or improvement. I don't like the current animation much either.

**Comment by elucent** [comment]
The current animation has been slowed by half, and there's now a config option to toggle it on or off. In a future release, I'll probably add some particles or something more interesting to it as well.
