### ISSUE TITLE
Crafting Growth Powder is consuming the pestle.

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#27]
Playing version 0.005 on a server, whether I craft the powder in a crafting table or just in my inventory, I don't get my pestle back afterwards. It just disappears with the other ingredients. The entry in the tablet seems to imply that it is not supposed to do that... so I thought I'd give you a heads up.

**Comment by elucent** [comment]
v0.005 has broken container item code, sorry about that. It's fixed in the IDE, but I was held up by rewriting and redoing the in-game docs to support localization. It should be fixed in the next release, later today.
