### ISSUE TITLE
Not sure if "Insanity" effect is broken or if I'm doing it wrong.

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#28]
It's the first spell staff I've made, so pretty early on, and I've tried shooting it - fully charged - at mobs in a variety of situations, and none of them resulted in any different behavior in the mobs attacking me even though the swathe of particles hit them dead on. I've tried almost at point blank range as well as a block or two away, with and without other mobs around - even hitting the same mob multiple times before giving up and going for a sword instead. I've also tried aiming at both their heads and their feet.

Am I doing something wrong or is this unintended?

**Comment by elucent** [comment]
It will only do something when other mobs are around, in which case mobs have a chance of attacking each other. It's not great for when you're in the heat of combat, but if you ever see a group of mobs that hasn't aggroed yet, you have a good chance of clearing out a few of them from it.

I'll boost the likelihood of its effects happening, and I might make it lose the player target, so it has to stand and wait a bit while it re-aggroes onto you.
