### ISSUE TITLE
Text entries for "The Mortar" pages have no localization

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#30]
https://gyazo.com/a17dafba85915ffc0d3d4035df3266bb

Continues for all three pages.

**Comment by Febilian** [comment]
Found more localization quirks!

https://gyazo.com/f78865d03aeb0286e528f2483de5b6b1

Every page after that one in the same entry also has a borked title localization.

**Comment by elucent** [comment]
Just fixed in my IDE!
