### ISSUE TITLE
Living Axe takes longer than expected to harvest a wooden object like a crafting table.

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#31]
I was surprised when an Efficiency II Living Axe took longer than punching the crafting table with my hands, anyways. Is it not detecting the table as a 'wooden' object somehow?

**Comment by Febilian** [comment]
It also takes a long while to chop Livingwood from Botania. Maybe the axe only checks for normal logs/planks right now?

**Comment by elucent** [comment]
It's because of a silly Forge bug that makes it so you effectively have to code your own ItemAxe class. I've just overridden the getStrVsBlock() function in the ItemLivingAxe class, which should make it function as it should.
