### ISSUE TITLE
Enemies killed solely by spells drop no experience orbs

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#32]
As in, if the mob is not at all hit by a player in other ways, and is killed only through damaging spell staff effects, no exp orbs drop, although it does drop its normal loot.

**Comment by elucent** [comment]
Working on it!

**Comment by elucent** [comment]
Well, this is a lot harder than I thought it would be. I'm not sure it's even possible. I'm closing this for now, but if I ever find out a way to change that, I'll add it in a future release.
