### ISSUE TITLE
Growth spell does not work on nether wart

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#37]
I mean to be fair, there aren't a whole lot of growth-related mechanics that DO affect nether wart, but... I was a little disappointed. Haha.

**Comment by elucent** [comment]
Yeah, sorry. The growth spell scans for anything that implements IGrowable, and nether wart doesn't do that. I could add a special case if you want me to, it might just come after I finish a few new features.

**Comment by Febilian** [comment]
Whatever works for you and isn't too much trouble, don't worry too much about it!

**Comment by werty1124** [comment]
I can do this quickly.

**Comment by werty1124** [comment]
Done
