### ISSUE TITLE
Opening the runic tablet while a staff is in the offhand causes weird behavior

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#41]
'Weird behavior' as in the staff decides to keep charging as though you're holding right click until you close out of the tablet, at which point the spell on the staff will immediately be cast. I'm just glad that I didn't have any block breaking spell active in my offhand at the time, heh. Otherwise I'd have a hole in my house.

I didn't know what else to title this because otherwise the entire bug report would have been in the title, and that would get long-winded pretty quickly.

**Comment by elucent** [comment]
Fixed!
