### ISSUE TITLE
Crash when infusing stick with flower dust

### ISSUE THREAD

**Issue by RaineAndrews** [elucent/Roots#42]
If you click like a madman (like I did) because you don't know where to click, you can put the dust into the infuser and pull the stick out before the infusion is done and crash your game.

forge 1987
roots 0.0006

**Comment by RaineAndrews** [comment]
[FML Roots Crash Log.zip](https://github.com/elucent/Roots/files/344394/FML.Roots.Crash.Log.zip)

Does this help?

**Comment by elucent** [comment]
Fixed in my IDE, it'll be in the next update today or tomorrow.
