### ISSUE TITLE
Possible to dupe empty/depleted staffs into full ones

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#47]
My staff I was using to try to grow some crops ran out of charge/durability usage, but it didn't go away in my hand - it just had a red "0" on it. I went into my inventory and right clicked it, expecting it to disappear as a glitched item, but instead I somehow grabbed a new identical staff where the old one was - with full durability. And it's working as though it were at full durability again as well.

If it makes a difference it had two levels of potency on it and no other modifiers.

Using 1.9.4 recommended Forge version - 12.17.0.1976 - and version 0.105 of Roots.

**Comment by elucent** [comment]
I used a potentially dangerous means of removing staffs that were out of durability. A fix should be available in the next update, but we _might_ add some new features first.

**Comment by Febilian** [comment]
Alright. As usual I will let you know if I find any other quirks that seem strange with the current released version!
