### ISSUE TITLE
Crystal staff imbuing does not take into account modifiers on the petal dusts used

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#48]
I had several petal dusts I used as the incense in the ritual, which each had at least two modifiers on them of various kinds, and NONE of said modifiers were applied to the final crystal staff's spell modes.

I tried three spells at once and not four, if it makes a difference. I can cycle through the spells(which were otherwise applied properly) but none of them have anything other than +0 on any modifiers.

**Comment by werty1124** [comment]
Editing your edits because they were part of #50 which is fixed now :)

**Comment by elucent** [comment]
The modifiers are taken into account, they just don't show up in the tooltip. Just fixed it.
