### ISSUE TITLE
Staffs don't do damage at all to any mobs

### ISSUE THREAD

**Issue by Febilian** [elucent/Roots#50]
Could this be related to the "PVP" issue I mentioned a while ago that was fixed? I made a rose's thorns spell staff and it isn't actually hurting anything no matter how close I am to my target. I thought it was the crystal staff at first but I don't think any staffs that do damage are properly working now.

I'm on a server where PVP is turned off and there does appear to be some stuff in the server log when I try to use a staff.

https://paste.ee/p/ev31k

**Comment by Febilian** [comment]
I'm going to try updating to version 1.10.2, if all of the 1.9.4 mods work or have updates. Single player seemed fine but we'll see if it works on a server or not.

This issue was not present in single player on 1.10.2, so I'm wondering if it's specific to the backwards compatibility with 1.9.4.

**Comment by werty1124** [comment]
This is due to trying to run client side code on a server. Specifically Minecraft.getMinecraft().currentScreen

**Comment by Febilian** [comment]
Any chance of this fix being released in the near future? I know Elucent said something about wanting to put in more features before another release but staffs not working is kind of a big deal IMO.

**Comment by elucent** [comment]
I said that because I didn't think there were such large bugs in the mod. I'll see what I can do.

**Comment by elucent** [comment]
I have a theory about why it's not working, but fixing it would probably involve making a separate config option for spell PvP. Would that be okay?

**Comment by Febilian** [comment]
Would it still be possible to use staffs at all, even with the config option for spell PVP disabled(as in, not hurting other players)? I don't mind if that's the case.

**Comment by elucent** [comment]
You would be able to use all staffs, except with the PVP-disabled option combat spells wouldn't work on players.

**Comment by Febilian** [comment]
Tried the 0.106 file and toggled the config option, still can't hurt mobs. It doesn't even work when the config ISN'T toggled, actually - I tested it both ways serverside.

I'm testing with a rose's thorns basic staff without any modifiers and I can't do a thing with it to creepers I spawned in.

**Comment by werty1124** [comment]
Same thing happening in ItemStaff that was happening in ItemCrystalStaff

**Comment by werty1124** [comment]
@Febilian try this one and let me know if it solves the issue 
[roots-0.106.zip](https://github.com/elucent/Roots/files/349045/roots-0.106.zip)

**Comment by Febilian** [comment]
Gonna try it now, though I can't test the PVP aspect of it as I have no one to test it with at the moment.

**Comment by werty1124** [comment]
It's fine it should fix the mob damage however

**Comment by Febilian** [comment]
It did so far, both with the config option enabled and disabled!

On a side note redcurrant appears to be missing its texture in the version you sent me, just poked in the creative menu and noticed the magenta-and-black checkerboard of doom.

**Comment by werty1124** [comment]
Yea I noticed that also. Not sure why it did in the compiled build it works fine in my IDE

**Comment by Febilian** [comment]
Well at the very least, it seems the issue with staffs not working has been resolved. I suppose I ought to wait for an official release of it now!

**Comment by werty1124** [comment]
Shouldn't be too long :p but don't hold us to that!
