### ISSUE TITLE
Suggestion: Aesthetic Standing Stone

### ISSUE THREAD

**Issue by malignantMystic** [elucent/Roots#51]
Miss clicked and deleted this sorry :/

**Comment by elucent** [comment]
How about I make all the existing standing stones toggleable with redstone, so they have to be powered to work?

**Comment by werty1124** [comment]
Something like this work http://imgur.com/a/T9NTR

**Comment by malignantMystic** [comment]
1) That would also be a great option!
2) That is...even more configurable than I could have possibly imagined I love it.

**Comment by werty1124** [comment]
It's pretty configurable you have practically the whole RGB spectrum
