### ISSUE TITLE
crash when I right click on the Root runic tablet when Weapons Case Loot is installed

### ISSUE THREAD

**Issue by Hypsellis** [elucent/Roots#53]
It seems that there is a conflict between Roots and Weapons Case Loot is installed wich causes minecraft to crash when I right click on the Roots runic tablet. http://pastebin.com/KchMUyDW

**Comment by werty1124** [comment]
This is something you should mention to the Weapons case loot dev it seems to be on his end.

**Comment by Hypsellis** [comment]
I already did it, I wait his answer. ;)
