### ISSUE TITLE
Server crash on summoning skeleton

### ISSUE THREAD

**Issue by F4ndroid** [elucent/Roots#54]
I forgot what the name of the spell is, but the one that spawns a skeleton to attack other mobs. I used it, instantly crashed the server and crashes every time I login.

https://breakfastcraft.com/crash/crash-2016-07-08_23.08.33-server.txt

**Comment by elucent** [comment]
Added a safety checker, so it won't crash anymore. The event that's crashing is supposed to be cancellable though...
