### ISSUE TITLE
Please update curseforge with all the links.

### ISSUE THREAD

**Issue by Claycorp** [elucent/Roots#55]
If you go into settings there will be some options for adding links to the issue tracker, source and a wiki if you have one.

Issue tracker is under Settings>Issues>External>put link to issues in box.
Source is under Settings>Source>Github>Put link in the box.
Wiki link is under Settings>General>all the way at the bottom.

This will add quick link buttons to the top of the page making it easy to find what is needed instead of searching in the post for the github link.

**Comment by elucent** [comment]
Updated the links, including updating the GitHub wiki with a somewhat passive-aggressive instruction to use the Runic Tablet :P.
