### ISSUE TITLE
Difficult to tell the difference between some of the barks in the tablet

### ISSUE THREAD

**Issue by gchpaco** [elucent/Roots#57]
I have trouble telling the difference between some of the barks (jungle, spruce and oak all look very similar to me) in the tablet when trying to set up for a ritual.  I *like* the current textures, but perhaps a tooltip detailing what the object is would be a good idea.

**Comment by elucent** [comment]
Shouldn't be too hard. I'll make tooltips for the next release, as you aren't the first to request this.

**Comment by elucent** [comment]
Tooltips have been added to all items in the GUI.
