### ISSUE TITLE
Shatter not accepting AOE increase modifier

### ISSUE THREAD

**Issue by VallenFrostweaver** [elucent/Roots#58]
When making a staff of Shatter and adding Gunpowder there is no change in the area of effect.

**Comment by elucent** [comment]
I'll add it to the next release. The gunpowder modifier will _currently_ increase the range at which you can break blocks, as it does with the Water Blast or Earth Spike spells with their respective effects, but I can see your confusion.

**Comment by elucent** [comment]
I have recoded the Earth Spike and Shatter spells to dynamically generate depending on the size modifier.
