### ISSUE TITLE
Skeleton summon crashes game

### ISSUE THREAD

**Issue by VallenFrostweaver** [elucent/Roots#59]
I made a level 3 potency staff to summon a skeleton to attack a zombie and was able to use it once. Second time crashed but recovered. 3rd time crashes every time. Included crash report.
[crash-2016-07-13_16.01.58-server.txt](https://github.com/elucent/Roots/files/361768/crash-2016-07-13_16.01.58-server.txt)

**Comment by VallenFrostweaver** [comment]
Was able to /kill myself fast enough on load in to escape the area. The spell is called Devil's Flower. Tried to then shoot the skeleton from a distance with a bow and crashed upon hitting it. Reloaded and hit it with an axe and all was fine though I am not casting that spell any time soon. ;)

**Comment by werty1124** [comment]
I believe @elucent has this fixed in the next version.

**Comment by VallenFrostweaver** [comment]
Cool thx.

**Comment by elucent** [comment]
Fixed, and now instead of just not crashing, it actually makes them attack still! They will sometimes get stuck and lose purpose, but what can you expect when you wrench skeletons out of the demonic plane?
