### ISSUE TITLE
Crash(from SimpleCore) when using(right-click) the Runic Tablet

### ISSUE THREAD

**Issue by Drakray** [elucent/Roots#60]
http://pastebin.com/bau8yFgE

posted on SimpleCore's github too
https://github.com/Sinhika/SimpleCore/issues/2

**Comment by Sinhika** [comment]
Please test  simplecore-1.9.4-1.3.5.38.jar which I just posted to CurseForge. If that doesn't fix the problem, I'll need a detailed report of what you were doing when the crash happened.

**Comment by Drakray** [comment]
Working perfectly (for now :P )

**Comment by elucent** [comment]
:D
