### ISSUE TITLE
Particles render before water

### ISSUE THREAD

**Issue by Kalman98** [elucent/Roots#61]
Particles from the staves render before water, which looks very broken. The particles look like they're behind the water even though they are not. I can't think of a better description.

**Comment by elucent** [comment]
Not really fixable. This happens with all translucent particles (e.g. lightning) that are designed to overlap each other. This is a vanilla Minecraft issue, sorry.

**Comment by Kalman98** [comment]
I hope you don't mind me commenting after this is closed, but that is too bad. This has made me decide to look into making a mod to fix particles.
