### ISSUE TITLE
Suggestion: Drumstick called "QuestLove"

### ISSUE THREAD

**Issue by ruyanve** [elucent/Roots#63]
To be honest, I have no idea what it should do, but it would be hilarious! Or maybe a comb to get string instead of wool from sheep?

**Comment by ShadowGamerXY** [comment]
Well I am sorry but for now I have to reject this suggestion, please don not take it in a bad way but we have a plan of what features items and basicly what content are we going to add in the future and also with bug fixes, polishing the mod, making it more compact and better. We just do not have time to add other thing that are not part of our plan.

**Comment by ruyanve** [comment]
All good, I only hope you know this was only a half serious pun about the band The Roots :-D
