### ISSUE TITLE
Some broken textures

### ISSUE THREAD

**Issue by blockbreaker1361** [elucent/Roots#64]
I don't know if you already know this, but there are some broken textures in your mod.
http://imgur.com/t1RL4Yy

**Comment by ShadowGamerXY** [comment]
I am looking into it right now.

**Comment by ShadowGamerXY** [comment]
The fix will be in the next update so stay tuned

**Comment by blockbreaker1361** [comment]
Thank you. :)

**Comment by ShadowGamerXY** [comment]
No problem m8 :)
