### ISSUE TITLE
[1.10.2] Items in hand displaying as Crystal Staff when beside in hotbar

### ISSUE THREAD

**Issue by dirtyfargo** [elucent/Roots#65]
Description: Other items render in hand as the Crystal Staff when beside it in the hot-bar, after having held the Crystal Staff, as shown in this gif:
![9c259f1f29240273603a0142b8165340](https://cloud.githubusercontent.com/assets/10457528/16901641/62f84ee2-4bfe-11e6-9d72-916702d85826.gif)
Version: 0.109.0
Forge: 12.18.1.2014
MC Version: 1.10.2

**Comment by werty1124** [comment]
I actually cant seem to be able to reproduce this, How many spells are on your staff? Which ones?

**Comment by dirtyfargo** [comment]
The staff only has 1 spell, Nature's Cure, with 3 efficiency modifiers, and also I'm on a server if that helps!

**Comment by dirtyfargo** [comment]
I can also make this occur with the Petal Dust, and probably other items too. There's a decent amount of other mods on my server as well though, so I realize that there's a chance it is not a bug from Roots. I could set up a stand alone instance/server with just this mod and test it out if you like?

**Comment by werty1124** [comment]
@dirtyfargo That would be helpful, I'm still able to reproduce this.

**Comment by dirtyfargo** [comment]
Alright well I don't seem to have this issue without other mods present as well, so I'm guessing it's nothing to do with Roots, sorry for the inconvenience. Not sure what's causing it though haha.
