### ISSUE TITLE
[1.10] Roots (roots) wants Minecraft [1.10.2,1.10.2]

### ISSUE THREAD

**Issue by OwningApple** [elucent/Roots#66]
Using forge-modloader 12.18.0.2000 for Minecraft 1.10, I encountered this error using both Roots versions 0.108.0 and 0.109.0 for Minecraft [1.10, 1.10.1, 1.10.2]
![ss 2016-07-17 at 06 29 12](https://cloud.githubusercontent.com/assets/20503601/16901784/3488fa58-4c4d-11e6-82dd-ea61a87f3662.png)

**Comment by werty1124** [comment]
It only works on 1.10.2 it will error if you try to use it on 1.10

**Comment by OwningApple** [comment]
I used the roots version minecraft 1.10 as it is found on minecraft curseforge

**Comment by elucent** [comment]
Due to some changes we've made with our version setup, I don't think we can support 1.10 and 1.10.1 any more.  Sorry about that :/
