### ISSUE TITLE
[1.10.2]Slime summoning causes a "crash"

### ISSUE THREAD

**Issue by superbrias** [elucent/Roots#67]
Done in the FTB Unstable 1.10.2 version. (version 4.2.3 of the modpack found on curse) Done in singleplayer.

I am willing to share a save and have a game log file prepared, any other resources, and these as well, you may ask for as you please and I shall provide ASAP.

have not tested the mod independently, but I have confirmed I can summon zombies and cows and make the grower stone, assuming that most other rituals work as well.

Basically I set up and activate an altar with the capabilities to summon a slime,(was planning on capturing it and using it for a spawner) but just as the particle effects seemed to draw to their end the game freezes up and stops responding, looking into the log it seems an error has occurred and the only solution is to force the game to close, while not officially a crash it is still just as impactful, luckily save returns to a point just before the ritual, or pretends the ritual did not start, (have not confirmed which) and is still usable.

excerpt of error trying to narrow the problem myself, remember I will provide the full log if you ask;
[22:31:59] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
. . .
Caused by: java.lang.ClassCastException: net.minecraft.entity.monster.EntitySlime cannot be cast to net.minecraft.entity.EntityCreature

**Comment by superbrias** [comment]
made sure the pack was using the most recent version and still got a crash
adding crash log here;
[crash-2016-07-18_20.16.55-server.txt](https://github.com/elucent/Roots/files/370605/crash-2016-07-18_20.16.55-server.txt)
(my quick check shows the crash log mentions the most recent version of the roots mod)

**Comment by elucent** [comment]
I have found your error, it's fixed in the next update.
