### ISSUE TITLE
invalid ritual

### ISSUE THREAD

**Issue by toddythebody** [elucent/Roots#69]
The banishrain and causerain rituals both give an invalid ritual error. I can get the rest to work. I'm playing on the Avant 3 mudpack.

**Comment by werty1124** [comment]
What version?

**Comment by toddythebody** [comment]
1.10.2-0.109.0

**Comment by werty1124** [comment]
They both now have to be above y 128 to work in that version

**Comment by toddythebody** [comment]
Ah. I see that now. Sorry to bother. I will include this info in a video. Thank you very much. There is some good work being done here on this mod.
