### ISSUE TITLE
Version 0.108 to 0.109

### ISSUE THREAD

**Issue by VallenFrostweaver** [elucent/Roots#71]
Probably not worth mentioning with how often you update but...
Version 0.109 when read by a loader (i.e. MultiMC or in Minecraft viewing the mod version) still shows the version number as 0.108 even though the .jar file is named 0.109. Strangely, the file is actually smaller in size than 0.108 too. Maybe there is something here worth an "Issue" report but I leave that to you to decide if there is something wrong or not.

**Comment by elucent** [comment]
I think we just forgot to change the number somewhere. It'll probably be fixed by v0.110.
