### ISSUE TITLE
Shatter not working

### ISSUE THREAD

**Issue by VallenFrostweaver** [elucent/Roots#72]
CORRECTION EDIT: No staff will work any longer when I switched from 0.107 to 0.109 as the Terra bars are completely missing. I can start a new play through and all is well. Not sure what could be causing this or if it's even worth your time. I was hoping that I didn't have to start over again and also thought it was worth a mention.

**Comment by elucent** [comment]
We did some changes regarding how terra works between 0.107 and 0.109. I can release an update with a command that will fix it if you like.

**Comment by VallenFrostweaver** [comment]
Yes please. If you don't mind. :D

**Comment by elucent** [comment]
I'll release a quick update shortly.
