### ISSUE TITLE
Regeneration staff heals w/out flowers?

### ISSUE THREAD

**Issue by VallenFrostweaver** [elucent/Roots#73]
In the description on the tablet it states that it may heal you drawing power from nearby flowers but going into the nether it still works. Perhaps it could be referring to the Peonies used in the petal dust or just from the surrounding elements? There are mushrooms there but... no flowers I know of.  Not so much a bug as much as a lore thing I guess. Feel free to close this if it's not an issue for you. :)

EDIT: I suppose Netherwart can be assumed a flower in this case?

**Comment by werty1124** [comment]
Basically any plant/mushroom will work
