### ISSUE TITLE
Horn of the Canopy from Botania doesn't drop extra drops

### ISSUE THREAD

**Issue by DreadBoy** [elucent/Roots#74]
It was suggested to me I should report that issue to both mods, Botania issue is https://github.com/williewillus/Botania/issues/399. I don't know the cause of this interaction but whenever I use Horn of the Wild (from Botania) in the forest or tree farm leaves don't drop any berries or currants, only saplings and/or apples. As far as I can tell, these drops don't require human interaction to drop.

**Comment by elucent** [comment]
The berries were changed in the most recent update to require human interaction to drop. It's intended so you don't get loads of berries when you don't want them, and also so you have to work a little to get that early-game food value from them.

**Comment by DreadBoy** [comment]
I'll update Roots to 0.108 and report what happens. But in 0.107 when logs are destroyed by Pulse Mana Spreader with Bore lens (non-human interaction, I assume) leaves still drop berries (just tested).

**Comment by DreadBoy** [comment]
Never mind, I just reread Runic Tablet entry in 0.108 and it says I need to break leaves by hand. Yes, problem was on my side, thanks for clearing up.
