### ISSUE TITLE
[1.10.2]Hold staff show no terra bar and staff not working properly

### ISSUE THREAD

**Issue by NanayaQ** [elucent/Roots#75]
So.. I updated to roots-1.10.2-0.109.0 and when I selected my staff there is no terra showing (the leaf bar) and when casting the staff it show the usage, however nothing happen. Tested with the staff that increase  tile entity tick.

**Comment by meradudd** [comment]
Having same issue with all staff casting.  Additionally, non-item generating rituals give me the terra bar, but the spell proper doesn't trigger or reduce the terra.  Running   0.108 on MC 1.10.2.

**Comment by werty1124** [comment]
Are either of you on a server?

**Comment by elucent** [comment]
I believe you lost your terra capabilities during the update, due to how we changed the capability code. I will release a small update later today with a few fixes, as well as a /roots setmaxterra <terra> command for you to reset your terra bar. Use a value of 40 terra to get it back to normal.

**Comment by Xiaminou** [comment]
Same problem, works fine in a new singleplayer world, but doesn't work on my server.

**Comment by werty1124** [comment]
If you were on an older world player with an older version of roots and updated you'll have to do what elucent said or delete the player file so it gets reset

**Comment by Xiaminou** [comment]
you don't have to delete the player file just do what I said.

**Comment by meradudd** [comment]
Sorry, should have mentioned.  SSP.  No server.

**Comment by werty1124** [comment]
@meradudd you can still fix it the same way. It's a bug from where we switched how those things are handled
