### ISSUE TITLE
Cannot Craft Utility Standing Stones

### ISSUE THREAD

**Issue by eawages3** [elucent/Roots#76]
Attempted 4 Times, Each time yields an Aesthetic Standing Stone.

**Comment by ShadowGamerXY** [comment]
You mean energized stones?

**Comment by ShadowGamerXY** [comment]
And on what version of the mod are you using?

**Comment by ShadowGamerXY** [comment]
Ok nevermind found the problem.

**Comment by ShadowGamerXY** [comment]
Now it is fixed and it will be in the next update. Have a good day.

**Comment by eawages3** [comment]
Thanks :)
You too
