### ISSUE TITLE
[1.10.2] Crash When Breaking Standing Stone 

### ISSUE THREAD

**Issue by Stuart74** [elucent/Roots#78]
When a player breaks the Standing Stone the server will crash for some reason. this has been reproducable we have tried multiple picks to see if its just a certain item that causes it or if its the enhances stone itself 

Roots Version roots-1.10.2-0.109.0
Forge Version 12.18.1.2014
Server Error On Crash: [Gist](https://gist.github.com/Stuart74/7e2dc57227d05eeeae415ebf7c80a691)

Really not sure why the error is referring to botania as there was no block being used for botania just roots

**Comment by elucent** [comment]
When the error references Botania, the error is related to Botania, so unfortunately this doesn't appear to be my fault. I'll look through the Botania code and see if I can fix it, in which case I'll PR it to williewillus' GitHub.

**Comment by Stuart74** [comment]
This has been referred back to you as a roots issue not a botania 

https://github.com/williewillus/Botania/issues/404#issuecomment-234787423

**Comment by williewillus** [comment]
^ I didn't say that above, but I concur with that assessment

whenever a type has a well-defined "empty" value like collections it's always better to return that than null

**Comment by Stuart74** [comment]
sorry i edited my reply if it was incorrect i just want an fix for this at the end of the day so any help is appreciated irrespective of which mod is causing it.

**Comment by williewillus** [comment]
I am surprised HarvestDropsEvent even lets a null collection through
