### ISSUE TITLE
Re Issue #78

### ISSUE THREAD

**Issue by Stuart74** [elucent/Roots#82]
please refer to https://github.com/elucent/Roots/issues/78

**Comment by elucent** [comment]
Fixed, sorry, forgot about how you said that it happened with other pickaxes as well. Vanilla should add better null checking :V

**Comment by yrsegal** [comment]
"vanilla should add nullchecking"

@Nonnull List<ItemStack> getDrops

**Comment by elucent** [comment]
It doesn't _have_ to be that way though.

**Comment by yrsegal** [comment]
you shouldn't return null from a nonnull method tho

**Comment by Stuart74** [comment]
When will this fix be available on curse ??

**Comment by elucent** [comment]
Probably later today, but I want to wait for another person on Curse to send me logs first so I can fix their bugs too.

**Comment by Stuart74** [comment]
Thanks for the help much appreciated :+1:

**Comment by Stuart74** [comment]
Just wondering regarding the update to this fix

**Comment by elucent** [comment]
I've been working on some new content for the next update and didn't want to spoil anything, so I didn't want to release any updates if I could avoid it. I _may_ have forgotten that this issue wasn't fixed in v0.110 though. I'll see if I can put together a release tomorrow.

**Comment by Stuart74** [comment]
No rush throw the fix in with your next planned update is fine i was just wondering thats all :)
