### ISSUE TITLE
1.10.2 Crash issue (First time occurance)

### ISSUE THREAD

**Issue by MrRagnorrock** [elucent/Roots#83]
Crash report from use of mod on a server. Crash occured when browsing the rituals for the energized ritual stones on the tablet.

[crash-2016-07-24_20.13.26-client.txt](https://github.com/elucent/Roots/files/380446/crash-2016-07-24_20.13.26-client.txt)

**Comment by MrRagnorrock** [comment]
Second time happening in the same place. Occurs after page for Vacuum ritual stone page.


[crash-2016-07-24_20.22.46-client.txt](https://github.com/elucent/Roots/files/380451/crash-2016-07-24_20.22.46-client.txt)

**Comment by MrRagnorrock** [comment]
Problem occurs in single player worlds as well, at the exact same place.

[crash-2016-07-24_20.27.48-client.txt](https://github.com/elucent/Roots/files/380453/crash-2016-07-24_20.27.48-client.txt)

**Comment by elucent** [comment]
Fixed, will be in the next release.
